name: heimdall
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  heimdall-otelcol:
    image: otel/opentelemetry-collector-contrib:0.102.0
    deploy:
      resources:
        limits:
          memory: 125M
    restart: always
    command: [ "--config=/etc/otelcol-config.yml" ]
    environment:
      - CLICKHOUSE_ENDPOINT=${CLICKHOUSE_ENDPOINT}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
    expose:
      - 4318
    ports:
      - "4317:4317"     # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint
    logging: *logging

  heimdall-ch:
    image: clickhouse/clickhouse-server:24.8.4-alpine
    user: '101:101'
    hostname: heimdall-ch
    restart: always
    volumes:
      - heimdall-ch-data:/var/lib/clickhouse
      - heimdall-ch-logs:/var/log/clickhouse-server
      - ./clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./clickhouse/docker-entrypoint-initdb.d/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    healthcheck:
      test: [ 'CMD-SHELL', 'clickhouse-client --query "SELECT 1"' ]
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  heimdall-db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - heimdall-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  heimdall-kv:
    image: redis:7.2.5-alpine
    restart: always
    volumes:
      - heimdall-kv-data:/data
    command: [ 'redis-server', '--maxmemory-policy', 'noeviction' ]
    ports:
      - 6379:6379

  heimdall-geo:
    image: observabilitystack/geoip-api:latest
    restart: always
    ports:
      - 8080:8080


volumes:
  heimdall-db-data:
    driver: local
  heimdall-kv-data:
    driver: local
  heimdall-ch-data:
    driver: local
  heimdall-ch-logs:
    driver: local
