version: "3.9"
name: heimdall
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otelcol
    deploy:
      resources:
        limits:
          memory: 125M
    restart: always
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"     # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint
    logging: *logging
