receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  # Clickhouse exporter
  clickhouse:
    endpoint: https://mqzfkj8vsu.eu-central-1.aws.clickhouse.cloud:8443?dial_timeout=10s&compress=lz4
    ttl_days: 3
    database: default
    username: default
    password: 9~IvVDZTVSyn_
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

processors:
  batch:
    timeout: 5s
    send_batch_size: 100000

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ clickhouse ]
